export enum Strings {
  name = 'Name',
  purchasePrice = 'Purchase price',
  sellingPrice = 'Selling price',
  averagePrice = 'Average price',
  reasonForPurchase = 'Reason for purchase',
  reasonForSale = 'Reason for sale',
  addPortfolio = 'Add Portfolio',
  addCoin = 'Add Coin',
  logIn = 'Log In',
  signUp = 'Sign Up',
  email = 'Email',
  password = 'Password',
  confirmPassword = 'Confirm Password',
  mustOneUpper = 'Must Contain One Uppercase Character',
  mustOneLower = 'Must Contain One Lowercase Character',
  mustOneNumber = 'Must Contain One Number Character',
  mustOneSpecial = 'Must Contain One Special Case Character',
  minPassword = 'Password must be at least 8 characters long',
  passwordsDontMatch = `Passwords Don't Match`,
}
